source 'http://rubygems.org'

gem 'rails', '3.2.1'
gem 'sqlite3'

gem 'paperclip'
gem 'coffee-script'
gem 'rocco'
gem 'uglifier'
gem 'jquery-rails'
gem 'ruby-debug19'
gem 'evergreen'
gem 'selenium-webdriver'
gem 'cucumber-rails'
gem 'fuubar-cucumber'
gem 'capybara'
gem 'capybara-firebug'
gem 'database_cleaner'
